apiVersion: v1

kind: Service

metadata:

  name: button-service

spec:

  selector:

    app: button-component

  ports:

    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000

  # type: ClusterIP
  type: NodePort
