name: Workflow Checks

on:

  push:

    branches-ignore:

      - main

jobs:

  linting:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code to prepare for merging 
        uses: actions/checkout@v2

      - name: Set up Python for testing project on remote server
        uses: actions/setup-python@v2
        with: python-version: 3.x

      - name: Install dependencies required for GitHub checks
        run: pip install flake8 pylint

      - name: Run code lint checks

        run: |

          # Run Flake8
          flake8 .

          # Or run pylint
          pylint utility.py constants.py
