name: Workflow Checks

on:

  push:

    branches-ignore:

      - main

jobs:

  linting:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code to prepare for linting tasks
        uses: actions/checkout@v2

      - name: Set up Python for checking project on remote server
        uses: actions/setup-python@v2

        with: 

          python-version: 3.10.9

      - name: Install dependencies required for GitHub checks
        run: pip install pylint pyppeteer

      - name: Run code lint checks for genetic algorithm directory
        run: pylint "genetic algorithm/**/*.py"

      - name: Run code lint checks for tic tac toe directory
        run: pylint "tic tac toe/**/*.py"

      - name: Run code linter for slither.io bot folder
        run: pylint "slither.io bot/**/*.py"

  testing:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code to prepare for testing
        uses: actions/checkout@v2

      - name: Configure python environment for running test cases
        uses: actions/setup-python@v2

        with:

          python-version: 3.10.9

      - name: Carry out unit testing
        run: |

          python "./genetic algorithm/test_utility.py"
          echo "ALL UNIT TESTS HAVE PASSED SUCCESSFULLY"

  building:

    runs-on: windows-latest

    steps:

      - name: Checkout code to host server for build checks
        uses: actions/checkout@v2

      - name: Set up Python on host machine
        uses: actions/setup-python@v2

        with:

          python-version: 3.10.9

      - name: Install all required dependencies for GitHub checks
        run: pip install -r "slither.io bot/requirements.txt"

      - name: Run code to ensure it builds with no errors that linting can't pick up
        run: |

          python "./genetic algorithm/evolve_word.py"
          echo "passed word evolution test case"
          python "./genetic algorithm/optimize_function.py"
          echo "passed function optimization test case"
          python "./genetic algorithm/search_manifold.py"
          echo "passed manifold search test case"
          python "./tic tac toe/utility.py"
          python "./slither.io bot/bot.py"
          echo "SUCCESSFULLY ALL BUILT PROJECTS"
