name: Workflow Checks

on:

  push:

    branches-ignore:

      - main

jobs:

  linting:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code to prepare for linting tasks
        uses: actions/checkout@v2

      - name: Set up Python for testing project on remote server
        uses: actions/setup-python@v2

        with: 

          python-version: 3.10.9

      - name: Install dependencies required for GitHub checks
        # run: pip install pylint
        run: pip install flake8

      - name: Run code lint checks
        # run: pylint ./**/*.py
        run: flake8 ./**/*.py

  testing:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code to prepare for testing
        uses: actions/checkout@v2

      - name: Configure python environment for running test cases
        uses: actions/setup-python@v2

        with:

          python-version: 3.10.9

      - name: Carry out unit testing
        run: python ./genetic algorithm/test_utility.py
