name: Workflow Checks

on:

  push:

    branches-ignore:

      - main

jobs:

  linting:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code to prepare for linting tasks
        uses: actions/checkout@v2

      - name: Set up Python for checking project on remote server
        uses: actions/setup-python@v2

        with: 

          python-version: 3.10.9

      - name: Install dependencies required for GitHub checks
        run: pip install pylint

      - name: Run code lint checks for genetic algorithm directory
        run: pylint "genetic algorithm/**/*.py"

      - name: Run code lint checks for tic tac toe directory
        run: pylint "tic tac toe/**/*.py"

  testing:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code to prepare for testing
        uses: actions/checkout@v2

      - name: Configure python environment for running test cases
        uses: actions/setup-python@v2

        with:

          python-version: 3.10.9

      - name: Carry out unit testing
        run: |

          python "./genetic algorithm/test_utility.py"
          echo "ALL TESTS HAVE PASSED SUCCESSFULLY"

  building:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code to host server for build checks
        uses: actions/checkout@v2

      - name: Set up Python on host machine
        uses: actions/setup-python@v2

        with:

          python-version: 3.10.9

      - name: Run code to ensure it builds with no errors that linting can't pick up
        run: |

          python "./genetic algorithm/utility.py"
          echo "SUCCESSFULLY BUILT PROJECT"
